[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn backend.mypyme.wsgi:application --bind 0.0.0.0:$PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10