[build]
builder = "nixpacks"

[deploy]
startCommand = "gunicorn backend.mypyme.wsgi:application --host 0.0.0.0 --port $PORT"
healthcheckPath = "/"
healthcheckTimeout = 100
restartPolicyType = "on_failure"
restartPolicyMaxRetries = 10